# Generated by Django 5.0.1 on 2024-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapIpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('sectors', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('application_date', models.CharField(max_length=200)),
                ('date_of_sebon', models.CharField(max_length=200)),
                ('issue_manager', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
